// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface Cliente {
    idCliente: number;
    nombre:    string;
    apellido:  string;
    correo:    string;
    telefono:  string;
}
